version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: F5rs9ku4h
      POSTGRES_DB: recipes
    ports:
      - "5432:5432"
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-java-springboot-app:latest
    environment:
      DB_URL: jdbc:postgresql://db:5432/recipes
      DB_USERNAME: postgres
      DB_PASSWORD: F5rs9ku4h
      DB_DRIVER: org.postgresql.Driver
    ports:
      - "8080:8080"
    depends_on:
      - db