-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

-- DROP SEQUENCE public.commentaries_id_seq;

CREATE SEQUENCE public.commentaries_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.ingredient_id_seq;

CREATE SEQUENCE public.ingredient_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.recipe_id_seq;

CREATE SEQUENCE public.recipe_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.users_id_seq;

CREATE SEQUENCE public.users_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- public.ingredient definition

-- Drop table

-- DROP TABLE public.ingredient;

CREATE TABLE public.ingredient (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NULL,
	CONSTRAINT ingredient_pkey PRIMARY KEY (id)
);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	user_type varchar(31) NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	email varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	username varchar(255) NOT NULL,
	user_id int8 NULL,
	CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
	CONSTRAINT uk6efs5vmce86ymf5q7lmvn2uuf UNIQUE (user_id),
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT fkqg2qcoumch2m4ok1cf8q675yu FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.recipe definition

-- Drop table

-- DROP TABLE public.recipe;

CREATE TABLE public.recipe (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	description varchar(255) NULL,
	image varchar(255) NULL,
	"name" varchar(255) NULL,
	preparation varchar(255) NULL,
	user_id int8 NULL,
	CONSTRAINT recipe_pkey PRIMARY KEY (id),
	CONSTRAINT fk5mx01yw4j003wisa2aqmwir6l FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.recipe_ingredient definition

-- Drop table

-- DROP TABLE public.recipe_ingredient;

CREATE TABLE public.recipe_ingredient (
	recipe_id int8 NOT NULL,
	ingredient_id int8 NOT NULL,
	CONSTRAINT recipe_ingredient_pkey PRIMARY KEY (recipe_id, ingredient_id),
	CONSTRAINT fk9b3oxoskt0chwqxge0cnlkc29 FOREIGN KEY (ingredient_id) REFERENCES public.ingredient(id),
	CONSTRAINT fkgu1oxq7mbcgkx5dah6o8geirh FOREIGN KEY (recipe_id) REFERENCES public.recipe(id)
);


-- public.commentaries definition

-- Drop table

-- DROP TABLE public.commentaries;

CREATE TABLE public.commentaries (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"comment" varchar(255) NOT NULL,
	"date" timestamp(6) NOT NULL,
	recipe_id int8 NULL,
	user_id int8 NULL,
	CONSTRAINT commentaries_pkey PRIMARY KEY (id),
	CONSTRAINT fk4w16kqj6nkij4kgohharsbmhq FOREIGN KEY (user_id) REFERENCES public.users(id),
	CONSTRAINT fkd55a4gm434f88qwvsxlwko2da FOREIGN KEY (recipe_id) REFERENCES public.recipe(id)
);